# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "Lemon")
Ingredient.create(name: "Ice")
Ingredient.create(name: "Mint leaves")
Ingredient.create(name: "Blackberry brandy")
Ingredient.create(name: "Peppermint schnapps")
Ingredient.create(name: "Pisco")
Ingredient.create(name: "Firewater")
Ingredient.create(name: "Peach nectar")
Ingredient.create(name: "Egg yolk")
Ingredient.create(name: "Apple cider")
Ingredient.create(name: "Angelica root")
Ingredient.create(name: "Espresso")
Ingredient.create(name: "Water")
Ingredient.create(name: "Ouzo")
Ingredient.create(name: "Peach Vodka")
Ingredient.create(name: "Galliano")
Ingredient.create(name: "Heavy cream")
Ingredient.create(name: "Chocolate")
Ingredient.create(name: "Cocoa powder")
Ingredient.create(name: "Tomato juice")
Ingredient.create(name: "Kiwi")
Ingredient.create(name: "Grapes")
Ingredient.create(name: "Berries")
Ingredient.create(name: "Cantaloupe")
Ingredient.create(name: "Ginger")
Ingredient.create(name: "Lime")
Ingredient.create(name: "Mango")
Ingredient.create(name: "Yoghurt")
Ingredient.create(name: "Strawberries")
Ingredient.create(name: "Sugar syrup")
Ingredient.create(name: "Rum")
Ingredient.create(name: "Grenadine")
Ingredient.create(name: "Cherry brandy")
Ingredient.create(name: "Carbonated water")
Ingredient.create(name: "Dubonnet Rouge")
Ingredient.create(name: "Añejo rum")
Ingredient.create(name: "Vodka")
Ingredient.create(name: "Tequila")
Ingredient.create(name: "Bourbon")
Ingredient.create(name: "Coffee liqueur")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "Amaretto")
Ingredient.create(name: "Dry Vermouth")
Ingredient.create(name: "Orange bitters")
Ingredient.create(name: "Strawberry schnapps")
Ingredient.create(name: "Apricot brandy")
Ingredient.create(name: "Gin")
Ingredient.create(name: "Light rum")
Ingredient.create(name: "Triple sec")




